<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ctlinlp-0977.cignitiglobal.com" name="com.mobile.automation.scripts.ValidateoutstandingbalancedisplayinKioskDashboard_TestId_524" tests="1" failures="1" timestamp="12 Dec 2018 06:27:24 GMT" time="844.352" errors="0">
  <testcase name="Validate_outstandingbalancedisplayinKioskDashboard_TestId_524" time="844.352" classname="com.mobile.automation.scripts.ValidateoutstandingbalancedisplayinKioskDashboard_TestId_524">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.mobile.automation.scripts.ValidateoutstandingbalancedisplayinKioskDashboard_TestId_524.Validate_outstandingbalancedisplayinKioskDashboard_TestId_524(ValidateoutstandingbalancedisplayinKioskDashboard_TestId_524.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Validate_outstandingbalancedisplayinKioskDashboard_TestId_524 -->
</testsuite> <!-- com.mobile.automation.scripts.ValidateoutstandingbalancedisplayinKioskDashboard_TestId_524 -->
